import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

// Generated by Next.js — auto-regenerated on dev/build, kept out of lint.
// Path is relative to the directory where ESLint runs (frontend/).
const GENERATED_IGNORES = [
  'next-env.d.ts',
];

const BUILD_IGNORES = [
  '.next/**',
  'node_modules/**',
  'frontend/.next/**',
  'backend/dist/**',
];

const VISUALIZER_IGNORES = [
  'src/components/visualizer/**',
];

export default [
  {
    ignores: [...BUILD_IGNORES, ...GENERATED_IGNORES, ...VISUALIZER_IGNORES],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [...GENERATED_IGNORES, ...VISUALIZER_IGNORES],
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'react/no-unescaped-entities': 'off',
    },
  },
];
